const basededatos = {
  generos: [
    { id: 1, nombre: "Ciencia Ficcion" },
    { id: 2, nombre: "Accion" },
    { id: 3, nombre: "Comedia" },
    { id: 4, nombre: "Drama" },
    { id: 5, nombre: "Terror" },
    { id: 6, nombre: "Suspenso" },
    { id: 7, nombre: "Aventura" },
    { id: 8, nombre: "Animacion" },
    { id: 9, nombre: "Fantasia" },
    { id: 10, nombre: "Documental" }
  ],
  
  directores: [
    { id: 1, nombre: "Lana Wachowski" },
    { id: 2, nombre: "Lilly Wachowski" },
    { id: 3, nombre: "Christopher Nolan" },
    { id: 4, nombre: "Quentin Tarantino" },
    { id: 5, nombre: "Damian Szifron" },
    { id: 6, nombre: "Juan Jose Campanella" },
    { id: 7, nombre: "Martin Scorsese" },
    { id: 8, nombre: "Greta Gerwig" },
    { id: 9, nombre: "Steven Spielberg" },
    { id: 10, nombre: "James Cameron" },
    { id: 11, nombre: "Stanley Kubrick" },
    { id: 12, nombre: "Alfred Hitchcock" },
    { id: 13, nombre: "Sofia Coppola" },
    { id: 14, nombre: "Guillermo del Toro" },
    { id: 15, nombre: "Pedro Almodovar" },
    { id: 16, nombre: "Bong Joon-ho" },
    { id: 17, nombre: "Denis Villeneuve" },
    { id: 18, nombre: "Peter Jackson" },
    { id: 19, nombre: "George Lucas" },
    { id: 20, nombre: "El Dev Que No Duerme" }
  ],

  criticos: [
    { id: 1, nombre: "Pipo Gorosito", edad: 60, pais: "Argentina" },
    { id: 2, nombre: "NaNdo", edad: 35, pais: "España" },
    { id: 3, nombre: "Catalina Dlugi", edad: 69, pais: "Argentina" },
    { id: 4, nombre: "Cacho de Neuquen", edad: 55, pais: "Argentina" },
    { id: 5, nombre: "Mr. Undefined", edad: 42, pais: "EEUU" },
    { id: 6, nombre: "Roger Ebert", edad: 70, pais: "EEUU" },
    { id: 7, nombre: "Susana Gimenez", edad: 80, pais: "Argentina" },
    { id: 8, nombre: "Promesa Resuelta", edad: 28, pais: "Mexico" },
    { id: 9, nombre: "Falso Booleano", edad: 31, pais: "Colombia" },
    { id: 10, nombre: "Arrayano", edad: 45, pais: "Chile" }
  ],

  peliculas: [
    { id: 1, nombre: "Matrix", anio: 1999, direccionSetFilmacion: { calle: "Calle Falsa", numero: 123, pais: "Australia" }, directores: [1, 2], generos: [1, 2] },
    { id: 2, nombre: "Inception", anio: 2010, direccionSetFilmacion: { calle: "Sueño", numero: 4, pais: "EEUU" }, directores: [3], generos: [1, 2, 6] },
    { id: 3, nombre: "Pulp Fiction", anio: 1994, direccionSetFilmacion: { calle: "Big Kahuna", numero: 99, pais: "EEUU" }, directores: [4], generos: [2, 4] },
    { id: 4, nombre: "Relatos Salvajes", anio: 2014, direccionSetFilmacion: { calle: "Ruta Nacional", numero: 3, pais: "Argentina" }, directores: [5], generos: [3, 4, 6] },
    { id: 5, nombre: "El Secreto de sus Ojos", anio: 2009, direccionSetFilmacion: { calle: "Tribunales", numero: 100, pais: "Argentina" }, directores: [6], generos: [4, 6] },
    { id: 6, nombre: "Goodfellas", anio: 1990, direccionSetFilmacion: { calle: "Mafia St", numero: 50, pais: "EEUU" }, directores: [7], generos: [4] },
    { id: 7, nombre: "Barbie", anio: 2023, direccionSetFilmacion: { calle: "Plastic", numero: 1, pais: "EEUU" }, directores: [8], generos: [3] },
    { id: 8, nombre: "Jurassic Park", anio: 1993, direccionSetFilmacion: { calle: "Isla Nublar", numero: 0, pais: "Costa Rica" }, directores: [9], generos: [1, 7] },
    { id: 9, nombre: "Titanic", anio: 1997, direccionSetFilmacion: { calle: "Oceano", numero: 404, pais: "Atlantico" }, directores: [10], generos: [4] },
    { id: 10, nombre: "The Shining", anio: 1980, direccionSetFilmacion: { calle: "Overlook", numero: 237, pais: "EEUU" }, directores: [11], generos: [5] },
    { id: 11, nombre: "Psycho", anio: 1960, direccionSetFilmacion: { calle: "Bates Motel", numero: 1, pais: "EEUU" }, directores: [12], generos: [5, 6] },
    { id: 12, nombre: "Lost in Translation", anio: 2003, direccionSetFilmacion: { calle: "Tokyo", numero: 55, pais: "Japon" }, directores: [13], generos: [3, 4] },
    { id: 13, nombre: "El Laberinto del Fauno", anio: 2006, direccionSetFilmacion: { calle: "Bosque", numero: 33, pais: "España" }, directores: [14], generos: [4, 9] },
    { id: 14, nombre: "Volver", anio: 2006, direccionSetFilmacion: { calle: "Mancha", numero: 12, pais: "España" }, directores: [15], generos: [3, 4] },
    { id: 15, nombre: "Parasite", anio: 2019, direccionSetFilmacion: { calle: "Sotano", numero: -1, pais: "Corea del Sur" }, directores: [16], generos: [4, 6] },
    { id: 16, nombre: "Dune", anio: 2021, direccionSetFilmacion: { calle: "Arrakis", numero: 101, pais: "Jordania" }, directores: [17], generos: [1, 7] },
    { id: 17, nombre: "El Señor de los Anillos", anio: 2001, direccionSetFilmacion: { calle: "Comarca", numero: 1, pais: "Nueva Zelanda" }, directores: [18], generos: [7, 9] },
    { id: 18, nombre: "Star Wars: Una Nueva Esperanza", anio: 1977, direccionSetFilmacion: { calle: "Tatooine", numero: 2, pais: "Tunez" }, directores: [19], generos: [1, 7] },
    { id: 19, nombre: "El Callback del Terror", anio: 2024, direccionSetFilmacion: { calle: "Node Modules", numero: 666, pais: "Servidor" }, directores: [20], generos: [5, 6, 10] },
    { id: 20, nombre: "Avatar", anio: 2009, direccionSetFilmacion: { calle: "Pandora", numero: 9, pais: "EEUU" }, directores: [10], generos: [1, 7] },
    { id: 21, nombre: "Interstellar", anio: 2014, direccionSetFilmacion: { calle: "Agujero Negro", numero: 0, pais: "Espacio" }, directores: [3], generos: [1, 4] },
    { id: 22, nombre: "Kill Bill", anio: 2003, direccionSetFilmacion: { calle: "Okinawa", numero: 88, pais: "Japon" }, directores: [4], generos: [2] },
    { id: 23, nombre: "Tiempo de Valientes", anio: 2005, direccionSetFilmacion: { calle: "Corrientes", numero: 348, pais: "Argentina" }, directores: [5], generos: [2, 3] },
    { id: 24, nombre: "El hijo de la novia", anio: 2001, direccionSetFilmacion: { calle: "Restaurante", numero: 45, pais: "Argentina" }, directores: [6], generos: [3, 4] },
    { id: 25, nombre: "Taxi Driver", anio: 1976, direccionSetFilmacion: { calle: "Times Square", numero: 1970, pais: "EEUU" }, directores: [7], generos: [4, 6] },
    { id: 26, nombre: "Lady Bird", anio: 2017, direccionSetFilmacion: { calle: "Sacramento", numero: 16, pais: "EEUU" }, directores: [8], generos: [3, 4] },
    { id: 27, nombre: "E.T.", anio: 1982, direccionSetFilmacion: { calle: "Suburbio", numero: 5, pais: "EEUU" }, directores: [9], generos: [1, 7] },
    { id: 28, nombre: "Terminator 2", anio: 1991, direccionSetFilmacion: { calle: "Fundicion", numero: 1000, pais: "EEUU" }, directores: [10], generos: [1, 2] },
    { id: 29, nombre: "2001: Odisea del Espacio", anio: 1968, direccionSetFilmacion: { calle: "Monolito", numero: 2001, pais: "Reino Unido" }, directores: [11], generos: [1] },
    { id: 30, nombre: "Vertigo", anio: 1958, direccionSetFilmacion: { calle: "Campanario", numero: 360, pais: "EEUU" }, directores: [12], generos: [6] },
    { id: 31, nombre: "Marie Antoinette", anio: 2006, direccionSetFilmacion: { calle: "Versalles", numero: 1, pais: "Francia" }, directores: [13], generos: [4] },
    { id: 32, nombre: "La Forma del Agua", anio: 2017, direccionSetFilmacion: { calle: "Laboratorio", numero: 42, pais: "Canada" }, directores: [14], generos: [4, 9] },
    { id: 33, nombre: "Todo sobre mi madre", anio: 1999, direccionSetFilmacion: { calle: "Gran Via", numero: 21, pais: "España" }, directores: [15], generos: [4] },
    { id: 34, nombre: "Snowpiercer", anio: 2013, direccionSetFilmacion: { calle: "Vias", numero: 1000, pais: "Republica Checa" }, directores: [16], generos: [1, 2] },
    { id: 35, nombre: "Blade Runner 2049", anio: 2017, direccionSetFilmacion: { calle: "Los Angeles", numero: 2049, pais: "Hungria" }, directores: [17], generos: [1, 6] },
    { id: 36, nombre: "El Hobbit", anio: 2012, direccionSetFilmacion: { calle: "Montaña Solitaria", numero: 1, pais: "Nueva Zelanda" }, directores: [18], generos: [7, 9] },
    { id: 37, nombre: "El Imperio Contraataca", anio: 1980, direccionSetFilmacion: { calle: "Hoth", numero: 5, pais: "Noruega" }, directores: [19], generos: [1, 7] },
    { id: 38, nombre: "Promesas Rotas: El Async/Await", anio: 2025, direccionSetFilmacion: { calle: "Localhost", numero: 8080, pais: "Internet" }, directores: [20], generos: [4, 5, 10] },
    { id: 39, nombre: "Batman: The Dark Knight", anio: 2008, direccionSetFilmacion: { calle: "Gotica", numero: 8, pais: "EEUU" }, directores: [3], generos: [2, 6] },
    { id: 40, nombre: "Inglourious Basterds", anio: 2009, direccionSetFilmacion: { calle: "Cine", numero: 1944, pais: "Alemania" }, directores: [4], generos: [2, 4] }
  ],

  calificaciones: [
    { critico: 1, pelicula: 4, puntuacion: 10 },
    { critico: 2, pelicula: 19, puntuacion: 0 }, 
    { critico: 3, pelicula: 7, puntuacion: 8 },
    { critico: 4, pelicula: 23, puntuacion: 9 },
    { critico: 5, pelicula: 38, puntuacion: 2 },
    { critico: 6, pelicula: 6, puntuacion: 10 },
    { critico: 7, pelicula: 9, puntuacion: 10 },
    { critico: 8, pelicula: 19, puntuacion: 9 },
    { critico: 9, pelicula: 1, puntuacion: 7 },
    { critico: 10, pelicula: 2, puntuacion: 8 },
    { critico: 1, pelicula: 24, puntuacion: 9 },
    { critico: 2, pelicula: 38, puntuacion: 1 },
    { critico: 3, pelicula: 14, puntuacion: 8 },
    { critico: 4, pelicula: 1, puntuacion: 10 },
    { critico: 5, pelicula: 2, puntuacion: 5 },
    { critico: 6, pelicula: 39, puntuacion: 9 },
    { critico: 7, pelicula: 26, puntuacion: 7 },
    { critico: 8, pelicula: 15, puntuacion: 10 },
    { critico: 9, pelicula: 35, puntuacion: 8 },
    { critico: 10, pelicula: 16, puntuacion: 9 }
  ]
};
export default basededatos;